// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zygwudyqegtuishrecwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5Z3d1ZHlxZWd0dWlzaHJlY3drIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4NzQ1NjksImV4cCI6MjA1NzQ1MDU2OX0.sNs8FHzGJu6tl-Rn6R5LOYPgvsPRpu3l5f6IYG-hz2U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);